pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm build --prod'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build --prod'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/picllary'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'


- task: AwsBeanstalkRelease@1
  inputs:
    awsaccessKey: 'AKIA3WZ2EHRUPVONGXRP'
    secretKey: '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'
    region: 'eu-central-1'
    applicationBundle: '$(System.DefaultWorkingDirectory)/**/*.zip'
    applicationName: 'PicllaryAdminWeb'
    environmentName: 'Picllaryapp-env'
    versionLabel: 'v20220125161702'